name: exampel-pipeline

on:
  push:
    branches:
      - main
      - AbdulDabbagh-patch-1
      
jobs:
    run-test:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v3
      
        - name: Setup Python
          uses: actions/setup-python@v4.3.1
